- include: "{{ symfony_deploy_playbook_dir }}/config/steps/composer.yml"
  when: symfony_run_composer

- include: "{{ symfony_deploy_playbook_dir }}/config/steps/assets.yml"
  when: symfony_run_assets_install

- include: "{{ symfony_deploy_playbook_dir }}/config/steps/assetic.yml"
  when: symfony_run_assetic_dump

- include: "{{ symfony_deploy_playbook_dir }}/config/steps/cache.yml"
  when: symfony_run_cache_clear_and_warmup

- include: "{{ symfony_deploy_playbook_dir }}/config/steps/doctrine.yml"
  when: symfony_run_doctrine_migrations

- include: "{{ symfony_deploy_playbook_dir }}/config/steps/mongodb.yml"
  when: symfony_run_mongodb_schema_update
