---
- name: Clear cache
  shell: chdir={{ansistrano_release_path.stdout}}
    SYMFONY_ENV={{symfony_env}} {{symfony_php_path}} {{symfony_console_path}} cache:clear --no-warmup {{symfony_cache_options}}

- name: Warm-up cache
  shell: chdir={{ansistrano_release_path.stdout}}
    SYMFONY_ENV={{symfony_env}} {{symfony_php_path}} {{symfony_console_path}} cache:warmup {{symfony_cache_options}}
